name: logbook_app_001
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  # Tambahan untuk Modul 4
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  mongo_dart: ^0.10.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Registrasi Aset
  assets:
    - assets/Gambar1.png
    - assets/Gambar2.png
    - assets/Gambar3.png
    - .env